/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageStudentsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhnguyen
 */
public class ManageStudentsJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    Business business;
    StudentProfile selectedStudent;

    /**
     * Creates new form ManageStudentsJPanel
     */
    public ManageStudentsJPanel(Business bz, JPanel jp) {
        this.CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnAddNUID = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblNUID = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Students ");

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "NUID", "Status"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblStudentMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblStudent);

        btnAddNUID.setText("Add NUID");
        btnAddNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNUIDActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblNUID.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblNUID.setForeground(new java.awt.Color(255, 255, 255));
        lblNUID.setText("NUID");

        btnBack.setText("<<Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNUID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNUID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddNUID)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)
                                .addGap(78, 78, 78))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAddNUID)
                    .addComponent(lblNUID)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(162, 162, 162))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMousePressed
        // TODO add your handling code here:
        int size = tblStudent.getRowCount();
        int selectedrow = tblStudent.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedStudent = (StudentProfile) tblStudent.getValueAt(selectedrow, 0);
        if (selectedStudent == null) {
            return;
        }
    }//GEN-LAST:event_tblStudentMousePressed

    private void btnAddNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNUIDActionPerformed
        // TODO add your handling code here:
        String nuid = txtNUID.getText().trim();

        if (nuid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an NUID.",
                    "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StudentDirectory sd = business.getStudentDirectory();
        if (sd.findStudentByNuid(nuid) != null) {
            JOptionPane.showMessageDialog(this, "A student with that NUID already exists.",
                    "Duplicate NUID", JOptionPane.WARNING_MESSAGE);
            return;
        }


        PersonDirectory personDir = business.getPersonDirectory();
        Person person = personDir.newPerson(nuid); // NUID is the unique person id
        person.setNuid(nuid);
        person.setName("");
        sd.newStudentProfile(person);

        JOptionPane.showMessageDialog(this,
                "NUID " + nuid + " added. The student can now sign up with this NUID.",
                "Saved", JOptionPane.INFORMATION_MESSAGE);

        txtNUID.setText("");
        refreshTable();
    
    }//GEN-LAST:event_btnAddNUIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedrow = tblStudent.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        StudentProfile sp = (StudentProfile) tblStudent.getValueAt(selectedrow, 0);
        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete student " + sp.getPerson().getName() + " (and any login)?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            UserAccount ua = business.getUserAccountDirectory().findUserAccount(sp.getPerson().getPersonId());
            if (ua != null) {
                business.getUserAccountDirectory().removeUserAccount(ua);
            }
            business.getStudentDirectory().removeStudent(sp);
            refreshTable();
            JOptionPane.showMessageDialog(this, "Student deleted.",
                    "Deleted", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNUID;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtNUID;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
       DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
       model.setRowCount(0);

       StudentDirectory sd = business.getStudentDirectory();
       UserAccountDirectory uad = business.getUserAccountDirectory();

       for (StudentProfile sp : sd.getStudentList()) {
            UserAccount ua = uad.findUserAccount(sp.getPerson().getPersonId());

            String status = "Pending sign-up";
            if (ua != null) {
                status = "Registered";
            }

            Object[] row = new Object[3];
            row[0] = sp;
            row[1] = sp.getPerson().getNuid();
            row[2] = status;
            model.addRow(row);
        }
    }
}
