package ui.ServiceCenter;

import model.*;
import ui.MainJFrame;
import javax.swing.JOptionPane;

/**
 * "Services" workflow: create a new service for the catalog. NetBeans GUI
 * Builder form (see AddServiceJPanel.form). Centered layout matching the PDF:
 * Back button top-left, centered title, centered form, centered Create button.
 * Cost is validated as a double and duration as an int.
 *
 * @author vyngo
 */
public class AddServiceJPanel extends javax.swing.JPanel {

    private final MainJFrame mainFrame;

    public AddServiceJPanel(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        onShow();
    }

    /** Called whenever the card is shown: pre-fills the next auto Service ID. */
    public void onShow() {
        txtServiceID.setText(String.valueOf(Business.getInstance().peekNextServiceID()));
    }

    private void createService() {
        String type     = txtServiceType.getText().trim();
        String costStr  = txtCost.getText().trim();
        String mechanic = txtMechanic.getText().trim();
        String durStr   = txtDuration.getText().trim();

        if (type.isEmpty() || costStr.isEmpty() || mechanic.isEmpty() || durStr.isEmpty()) {
            error("All fields are required. Please fill in every field.");
            return;
        }
        double cost;
        try {
            cost = Double.parseDouble(costStr);
            if (cost < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            error("Cost must be a positive number (e.g., 49.99).");
            return;
        }
        int duration;
        try {
            duration = Integer.parseInt(durStr);
            if (duration <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            error("Service Duration must be a positive whole number of minutes.");
            return;
        }
        Service s = Business.getInstance().addService(type, cost, mechanic, duration);
        JOptionPane.showMessageDialog(this,
                "Service created successfully!\nAssigned Service ID: " + s.getServiceID(),
                "Success", JOptionPane.INFORMATION_MESSAGE);
        txtServiceType.setText("");
        txtCost.setText("");
        txtMechanic.setText("");
        txtDuration.setText("");
        onShow();
    }

    private void error(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Validation Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        lblServiceID = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        lblServiceType = new javax.swing.JLabel();
        txtServiceType = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblMechanic = new javax.swing.JLabel();
        txtMechanic = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 245));
        setLayout(new java.awt.BorderLayout());

        header.setOpaque(false);
        header.setLayout(new java.awt.GridBagLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 8, 10);
        header.add(btnBack, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        lblTitle.setText("Services");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 8, 120);
        header.add(lblTitle, gridBagConstraints);

        add(header, java.awt.BorderLayout.NORTH);

        form.setOpaque(false);
        form.setLayout(new java.awt.GridBagLayout());

        lblServiceID.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblServiceID.setText("Service ID :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(lblServiceID, gridBagConstraints);

        txtServiceID.setEditable(false);
        txtServiceID.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(txtServiceID, gridBagConstraints);

        lblServiceType.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblServiceType.setText("Service Type :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(lblServiceType, gridBagConstraints);

        txtServiceType.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(txtServiceType, gridBagConstraints);

        lblCost.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCost.setText("Cost :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(lblCost, gridBagConstraints);

        txtCost.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(txtCost, gridBagConstraints);

        lblMechanic.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMechanic.setText("Mechanic's Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(lblMechanic, gridBagConstraints);

        txtMechanic.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(txtMechanic, gridBagConstraints);

        lblDuration.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblDuration.setText("Service Duration :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(lblDuration, gridBagConstraints);

        txtDuration.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        form.add(txtDuration, gridBagConstraints);

        btnCreate.setText("Create Service");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 10, 10);
        form.add(btnCreate, gridBagConstraints);

        add(form, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showPanel(MainJFrame.WORK_AREA);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        createService();
    }//GEN-LAST:event_btnCreateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblMechanic;
    private javax.swing.JLabel lblServiceID;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtMechanic;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
