package ui.ServiceCenter;

import ui.MainJFrame;

/**
 * Landing card: a lavender navigation bar with the three workflow buttons over
 * a periwinkle welcome area. NetBeans GUI Builder form (see WorkAreaJPanel.form).
 *
 * @author vyngo
 */
public class WorkAreaJPanel extends javax.swing.JPanel {

    private final MainJFrame mainFrame;

    public WorkAreaJPanel(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        navBar = new javax.swing.JPanel();
        btnServices = new javax.swing.JButton();
        btnVehicleOwner = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        pnlWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        navBar.setBackground(new java.awt.Color(204, 204, 245));
        navBar.setLayout(new java.awt.GridBagLayout());

        btnServices.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        btnServices.setText("Services");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 18, 15);
        navBar.add(btnServices, gridBagConstraints);

        btnVehicleOwner.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        btnVehicleOwner.setText("Vehicle & Owner");
        btnVehicleOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleOwnerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 18, 15);
        navBar.add(btnVehicleOwner, gridBagConstraints);

        btnManage.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        btnManage.setText("Manage Vehicles");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 18, 15);
        navBar.add(btnManage, gridBagConstraints);

        add(navBar, java.awt.BorderLayout.NORTH);

        pnlWelcome.setBackground(new java.awt.Color(130, 130, 240));
        pnlWelcome.setLayout(new java.awt.GridBagLayout());

        lblWelcome.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        lblWelcome.setText("Welcome to Vehicle Service Management Application");
        pnlWelcome.add(lblWelcome, new java.awt.GridBagConstraints());

        add(pnlWelcome, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        mainFrame.showPanel(MainJFrame.SERVICES);
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnVehicleOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleOwnerActionPerformed
        mainFrame.showPanel(MainJFrame.VEHICLE_OWNER);
    }//GEN-LAST:event_btnVehicleOwnerActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        mainFrame.showPanel(MainJFrame.MANAGE_VEHICLES);
    }//GEN-LAST:event_btnManageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnVehicleOwner;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel pnlWelcome;
    // End of variables declaration//GEN-END:variables
}
