/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployeeDirectory;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    Business business;
    ManagePersonsJPanel parent;

    public AdministerPersonJPanel(Business bz, JPanel jp, ManagePersonsJPanel parent) {

        CardSequencePanel = jp;
        this.business = bz;
        this.parent = parent;
        initComponents();


    }

    public void refreshTable() {
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPersonTitle = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmployeeTitle = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 360, 80, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Person Profile (Employee Registration)");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(140, 360, 72, 23);
        add(txtPassword);
        txtPassword.setBounds(170, 310, 170, 23);
        add(txtFullName);
        txtFullName.setBounds(170, 70, 260, 23);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(40, 310, 130, 20);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        add(lblEmail);
        lblEmail.setBounds(40, 110, 130, 20);
        add(txtPersonTitle);
        txtPersonTitle.setBounds(170, 190, 260, 23);
        add(txtEmail);
        txtEmail.setBounds(170, 110, 260, 23);

        lblEmployeeTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEmployeeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeTitle.setText("Title");
        add(lblEmployeeTitle);
        lblEmployeeTitle.setBounds(40, 190, 110, 20);
        add(txtUserName);
        txtUserName.setBounds(170, 270, 260, 23);

        lblFullName.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("Full Name");
        add(lblFullName);
        lblFullName.setBounds(40, 70, 130, 20);

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone");
        add(lblPhone);
        lblPhone.setBounds(40, 150, 100, 17);
        add(txtDepartment);
        txtDepartment.setBounds(170, 230, 260, 23);
        add(txtPhone);
        txtPhone.setBounds(170, 150, 160, 23);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username");
        add(lblUserName);
        lblUserName.setBounds(40, 270, 130, 20);

        lblDepartment.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department");
        add(lblDepartment);
        lblDepartment.setBounds(40, 230, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtFullName.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String title = txtPersonTitle.getText();
        String department = txtDepartment.getText();
        String username = txtUserName.getText();
        String password = txtPassword.getText();

        if (name.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, user name and password are required.",
                    "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UserAccountDirectory uad = business.getUserAccountDirectory();
        if (uad.isUsernameTaken(username)) {
            JOptionPane.showMessageDialog(this, "That user name is already taken.",
                    "User Name Unavailable", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PersonDirectory personDir = business.getPersonDirectory();
        Person person = personDir.newPerson(name);
        person.setName(name);
        person.setEmail(email);
        person.setPhoneNumber(phone);

        EmployeeDirectory ed = business.getEmployeeDirectory();
        EmployeeProfile ep = ed.newEmployeeProfile(person);
        ep.setTitle(title);
        ep.setDepartment(department);

        uad.newUserAccount(ep, username, password);

        JOptionPane.showMessageDialog(this, "Employee registered successfully.",
                "Saved", JOptionPane.INFORMATION_MESSAGE);

        parent.refreshTable();
        
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    
       
    
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeTitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPersonTitle;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
