package ui;

import java.awt.CardLayout;
import model.Business;
import ui.ServiceCenter.AddServiceJPanel;
import ui.ServiceCenter.AddVehicleJPanel;
import ui.ServiceCenter.ManageVehiclesJPanel;
import ui.ServiceCenter.WorkAreaJPanel;

/**
 * Main application window. NetBeans GUI Builder form (see MainJFrame.form):
 * the content pane holds a single userProcessContainer panel that uses
 * CardLayout to swap between the landing menu and the three workflow panels.
 *
 * @author vyngo
 */
public class MainJFrame extends javax.swing.JFrame {

    public static final String WORK_AREA       = "WorkArea";
    public static final String SERVICES        = "Services";
    public static final String VEHICLE_OWNER   = "VehicleOwner";
    public static final String MANAGE_VEHICLES = "ManageVehicles";

    public MainJFrame() {
        initComponents();

        Business.getInstance().seedData();

        userProcessContainer.add(new WorkAreaJPanel(this), WORK_AREA);
        userProcessContainer.add(new AddServiceJPanel(this), SERVICES);
        userProcessContainer.add(new AddVehicleJPanel(this), VEHICLE_OWNER);
        userProcessContainer.add(new ManageVehiclesJPanel(this), MANAGE_VEHICLES);

        showPanel(WORK_AREA);

        setSize(920, 660);
        setLocationRelativeTo(null);
    }

    /** Switches the visible card, refreshing the target panel's data first. */
    public void showPanel(String name) {
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        for (java.awt.Component c : userProcessContainer.getComponents()) {
            if (name.equals(MANAGE_VEHICLES) && c instanceof ManageVehiclesJPanel) {
                ((ManageVehiclesJPanel) c).refreshTable();
            } else if (name.equals(VEHICLE_OWNER) && c instanceof AddVehicleJPanel) {
                ((AddVehicleJPanel) c).onShow();
            } else if (name.equals(SERVICES) && c instanceof AddServiceJPanel) {
                ((AddServiceJPanel) c).onShow();
            }
        }
        cl.show(userProcessContainer, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle Service Management Application");

        userProcessContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(userProcessContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        // Use the cross-platform (Metal) look and feel so the flat white
        // buttons and custom panel colours render exactly like the design.
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
