/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Person.Person;
import Business.Profiles.FacultyProfile;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anhnguyen
 */
public class FacultyMyProfileJPanel extends javax.swing.JPanel {
    UserAccount userAccount;
    JPanel CardSequencePanel;

    /**
     * Creates new form FacultyProfileJPanel
     */
    public FacultyMyProfileJPanel(UserAccount ua, JPanel clp) {
        this.userAccount = ua;
        this.CardSequencePanel = clp;
        initComponents();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminTitle1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblLastAccess = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFacultyTitle = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();
        lblTitleValue = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        lblDepartmentValue = new javax.swing.JLabel();
        lblPhoneValue = new javax.swing.JLabel();
        lblUserNameValue = new javax.swing.JLabel();
        lblLastAccessValue = new javax.swing.JLabel();
        lblRoleValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        lblAdminTitle1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblAdminTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminTitle1.setText("Department");

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone");

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");

        lblLastAccess.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblLastAccess.setForeground(new java.awt.Color(255, 255, 255));
        lblLastAccess.setText("Last Access");

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("My Profile (Faculty)");

        lblFacultyTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblFacultyTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFacultyTitle.setText("Title");

        lblNameValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblNameValue.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTitleValue.setForeground(new java.awt.Color(255, 255, 255));

        lblEmailValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblEmailValue.setForeground(new java.awt.Color(255, 255, 255));

        lblDepartmentValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblDepartmentValue.setForeground(new java.awt.Color(255, 255, 255));

        lblPhoneValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPhoneValue.setForeground(new java.awt.Color(255, 255, 255));

        lblUserNameValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblUserNameValue.setForeground(new java.awt.Color(255, 255, 255));

        lblLastAccessValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblLastAccessValue.setForeground(new java.awt.Color(255, 255, 255));

        lblRoleValue.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblRoleValue.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblName)
                                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdminTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLastAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFacultyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitleValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastAccessValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhoneValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDepartmentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRoleValue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblNameValue))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(lblRoleValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyTitle)
                    .addComponent(lblTitleValue))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminTitle1)
                    .addComponent(lblDepartmentValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblEmailValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(lblPhoneValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(lblUserNameValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastAccess)
                    .addComponent(lblLastAccessValue))
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAdminTitle1;
    private javax.swing.JLabel lblDepartmentValue;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblFacultyTitle;
    private javax.swing.JLabel lblLastAccess;
    private javax.swing.JLabel lblLastAccessValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneValue;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleValue;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserNameValue;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        FacultyProfile profile = (FacultyProfile) userAccount.getAssociatedPersonProfile();
        Person person = profile.getPerson();

        lblNameValue.setText(person.getName());
        lblRoleValue.setText(profile.getRole());
        lblTitleValue.setText(profile.getTitle());
        lblDepartmentValue.setText(profile.getDepartment());
        lblEmailValue.setText(person.getEmail());
        lblPhoneValue.setText(person.getPhoneNumber());
        lblUserNameValue.setText(userAccount.getUserLoginName());
        lblLastAccessValue.setText(userAccount.getLastAccessText());
    }
}
