/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Person.Person;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * h
 *
 * @author kal bugrara
 */
public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    UserAccount selecteduseraccount;
    ManageUserAccountsJPanel parent;

    public AdminUserAccount(UserAccount sua, JPanel jp, ManageUserAccountsJPanel parent) {
        initComponents();
        this.CardSequencePanel = jp;
        this.selecteduseraccount = sua;
        this.parent = parent;

        populate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblLastUpdated = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblLastAccess = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        lblRoleValue = new javax.swing.JLabel();
        lblLastUpdatedValue = new javax.swing.JLabel();
        lblLastAccessValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(490, 410, 100, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Administer User Account");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(50, 410, 100, 23);

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role");
        add(lblRole);
        lblRole.setBounds(50, 100, 80, 20);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        add(lblUserName);
        lblUserName.setBounds(50, 180, 110, 20);

        lblLastUpdated.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblLastUpdated.setForeground(new java.awt.Color(255, 255, 255));
        lblLastUpdated.setText("Last Updated");
        add(lblLastUpdated);
        lblLastUpdated.setBounds(50, 310, 100, 20);

        lblName.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(50, 140, 44, 20);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(50, 220, 100, 20);

        lblLastAccess.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblLastAccess.setForeground(new java.awt.Color(255, 255, 255));
        lblLastAccess.setText("Last Access");
        add(lblLastAccess);
        lblLastAccess.setBounds(50, 270, 88, 20);
        add(txtName);
        txtName.setBounds(220, 140, 120, 23);
        add(txtPassword);
        txtPassword.setBounds(220, 220, 120, 23);
        add(txtUserName);
        txtUserName.setBounds(220, 180, 120, 23);

        lblRoleValue.setForeground(new java.awt.Color(255, 255, 255));
        add(lblRoleValue);
        lblRoleValue.setBounds(220, 100, 80, 17);

        lblLastUpdatedValue.setForeground(new java.awt.Color(255, 255, 255));
        add(lblLastUpdatedValue);
        lblLastUpdatedValue.setBounds(220, 310, 270, 20);

        lblLastAccessValue.setForeground(new java.awt.Color(255, 255, 255));
        add(lblLastAccessValue);
        lblLastAccessValue.setBounds(220, 270, 300, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String username = txtUserName.getText();
        String password = txtPassword.getText();

        if (name.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, user name and password cannot be empty.",
                    "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
        person.setName(name);
        selecteduseraccount.setUserLoginName(username);
        selecteduseraccount.setPassword(password);

        // show the new "last updated" time
        lblLastUpdatedValue.setText(selecteduseraccount.getLastUpdatedText());

        parent.refreshTable();

        JOptionPane.showMessageDialog(this, "Account updated successfully.",
                "Saved", JOptionPane.INFORMATION_MESSAGE);
    


        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblLastAccess;
    private javax.swing.JLabel lblLastAccessValue;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblLastUpdatedValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
        lblRoleValue.setText(selecteduseraccount.getRole());
        txtName.setText(person.getName());
        txtUserName.setText(selecteduseraccount.getUserLoginName());
        txtPassword.setText(selecteduseraccount.getPassword());
        lblLastAccessValue.setText(selecteduseraccount.getLastAccessText());
        lblLastUpdatedValue.setText(selecteduseraccount.getLastUpdatedText());
    }

}
