/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;

    public ManageUserAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();

        refreshTable();

    }

    public void refreshTable() {

//clear supplier table
        int rc = tblUserAccounts.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblUserAccounts.getModel()).removeRow(i);
        }

        UserAccountDirectory uad = business.getUserAccountDirectory();

        for (UserAccount ua : uad.getUserAccountList()) {

            Object[] row = new Object[5];
            row[0] = ua;
            row[1] = ua.getRole();
            row[2] = ua.getAssociatedPersonProfile().getPerson().getName();
            row[3] = ua.getLastAccessText();
            row[4] = ua.getLastUpdatedText();
            ((DefaultTableModel) tblUserAccounts.getModel()).addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        lblUsersAccounts = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnViewUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(632, 482));
        setSize(new java.awt.Dimension(632, 482));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(530, 310, 80, 23);

        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        add(btnAddNew);
        btnAddNew.setBounds(30, 310, 90, 23);

        lblUsersAccounts.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsersAccounts.setForeground(new java.awt.Color(255, 255, 255));
        lblUsersAccounts.setText("User Accounts");
        add(lblUsersAccounts);
        lblUsersAccounts.setBounds(20, 80, 190, 17);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage User Accounts");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        ScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblUserAccountsMousePressed(evt);
            }
        });

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User Name", "Status", "Person", "Last Activity", "Last Updated"
            }
        ));
        ScrollPane.setViewportView(tblUserAccounts);
        if (tblUserAccounts.getColumnModel().getColumnCount() > 0) {
            tblUserAccounts.getColumnModel().getColumn(1).setResizable(false);
            tblUserAccounts.getColumnModel().getColumn(1).setHeaderValue("Status");
        }

        add(ScrollPane);
        ScrollPane.setBounds(10, 110, 640, 160);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(260, 310, 80, 23);

        btnViewUpdate.setText("View/Update");
        btnViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateActionPerformed(evt);
            }
        });
        add(btnViewUpdate);
        btnViewUpdate.setBounds(140, 310, 105, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        AddUserAccountJPanel addPanel = new AddUserAccountJPanel(business, CardSequencePanel, this);
        CardSequencePanel.add("AddUserAccount", addPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblUserAccounts.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        selecteduseraccount = (UserAccount) tblUserAccounts.getValueAt(selectedrow, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete account " + selecteduseraccount.getUserLoginName() + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            business.getUserAccountDirectory().removeUserAccount(selecteduseraccount);
            refreshTable();
            JOptionPane.showMessageDialog(this, "Account deleted.",
                    "Deleted", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblUserAccounts.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        selecteduseraccount = (UserAccount) tblUserAccounts.getValueAt(selectedrow, 0);

        AdminUserAccount detail = new AdminUserAccount(selecteduseraccount, CardSequencePanel, this);
        CardSequencePanel.add("AdminUserAccount", detail);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnViewUpdateActionPerformed

    private void tblUserAccountsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserAccountsMousePressed
        // TODO add your handling code here:
        int size = tblUserAccounts.getRowCount();
        int selectedrow = tblUserAccounts.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) tblUserAccounts.getValueAt(selectedrow, 0);
        if (selecteduseraccount == null) {
            return;
        }
    }//GEN-LAST:event_tblUserAccountsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewUpdate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsersAccounts;
    private javax.swing.JTable tblUserAccounts;
    // End of variables declaration//GEN-END:variables

}
